# Generated by Django 4.2.5 on 2023-10-06 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='provider_url',
        ),
    ]
